Fix unicode() not defined in test
Also refactor to use os.path.join()

======================================================================
ERROR: test_unicode_file_name (__main__.bbTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testwipe.py", line 195, in test_unicode_file_name
    file_path = unicode(test_folder + os.sep) + file_name_unicode
NameError: name 'unicode' is not defined