Fix test fir Python 3
======================================================================
ERROR: test_well_compressed_file_wipe (__main__.bbTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testwipe.py", line 232, in test_well_compressed_file_wipe
    write_compressable_test_file(file_path, 5 * 1024**2)
  File "testwipe.py", line 58, in write_compressable_test_file
    f.write(''.rjust(file_size, '|'))
TypeError: 'str' does not support the buffer interface

-------------------------------------------------------